# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Takahiro Hirofuchi
tagline:             'Senior Researcher of AIST'
description:         ''
url:                 http://takahiro-hirofuchi.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Takahiro Hirofuchi
  url:               https://twitter.com/mdo
  email:             t.hirofuchi _at_ aist.go.jp

# Custom vars
version:             1.0.0
